name: Auto Post

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: pip install -r requirements.txt

      - run: python autopost.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          RAWG_API_KEY: ${{ secrets.RAWG_API_KEY }}
